### ISSUE TITLE
若配置好环境后运行仍抛出异常, 请参考此方法

### ISSUE THREAD

**Issue by GoogTech** [YUbuntu0109/SSM-SMS#15]
### 第一个错误分析
1. 下载项目后，打开idea( 我的是2019.2 )，点击 open 打开该项目，等 maven 下载完毕 jar 包后即可配置Tomact
2. 然后点击运行时会抛出异常，并且在 applicationContext.xml 文件中会有这三处爆红，如下图所示 : 

> 原因 : 无法加载相应的配置文件，即没有找到指定的配置文件

解决办法 : 将 resource 文件重命名为 `resources` 并将 resources 下的文件都设置为 `resources root` 类型，除了 mapper 文件夹哟( 设置办法 : 右击 resources 文件夹 ---> Mark Directory as ---> resources root )

> 知识扩展 : [idea中文件夹的分类](https://blog.csdn.net/a772304419/article/details/79680775)

![image](https://user-images.githubusercontent.com/43493852/85758531-00109500-b743-11ea-8f3b-4596dc61e0ac.png)
![image](https://user-images.githubusercontent.com/43493852/85758546-030b8580-b743-11ea-8174-ccdf30e94d34.png)

### 第二个错误分析
第一个常见错误解决了，若运行后还会报错那应该就是数据库的问题了，错误信息及解决方法如下所示：
![image](https://user-images.githubusercontent.com/43493852/85758996-639ac280-b743-11ea-93e0-973fd5199916.png)

>  注意数据库的版本，若 mysql 版本低于 `8` 的话就要修改代码中的数据库配置信息哟

1. 修改数据库配置信息 : 先逐个复制表结构和语句，去掉编码部分( 我的mysql是5.0.51 ).  首先打开数据库配置文件 c3p0.properties 将  `com.mysql.cj.jdbc.Driver` 改为  `com.mysql.jdbc.Driver`

2. 更新 pom.xml 文件中的 `mysql-connector-java` 版本
并在下面加上
```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.0.5< version>
</dependency>
```

### 第三个错误分析
 一和二问题解决后就可以成功地运行该项目了，但是会发现使用名为 `黄宇辉` 的账户信息登录时会无法登录 ! 这是因为中文乱码的问题，自行在相应数据表中使用英文字母新建用户信息后，重新登录即可.

> it's so embarrassed that this project had a lot of bugs but thanks for your issue and  solution : @`2938543506@qq.com`

**Comment by emanresu112358** [comment]
修改了tb_admin表里面的数据，运行登陆弹出“登陆失败！服务器发生异常”，这个怎么解决呀？

**Comment by GuiterBoy** [comment]
请检查数据库是否链接成功.

**Comment by emanresu112358** [comment]
数据库是链接成功
<img width="1054" alt="截屏2022-06-11 22 39 14" src="https://user-images.githubusercontent.com/58353879/173192465-45b4b0ec-c6d4-49e1-bd07-2d8d5bc32d69.png">

**Comment by emanresu112358** [comment]
我的环境是macOS，我是不是路径错了啊。。。

**Comment by GuiterBoy** [comment]
上图 只 能 表示idea工具链接mysql数据库是成功的, 并不代表后端项目已成功链接数据库, 请检查数据库配置文件, 是否正确改写数据库用户名及密码. 祝好运. 晚安好梦.

**Comment by emanresu112358** [comment]
配置文件已经改好了
<img width="1037" alt="截屏2022-06-11 22 49 10" src="https://user-images.githubusercontent.com/58353879/173192754-de6dcbec-7819-4c7c-b869-7eaba36097ca.png">

**Comment by emanresu112358** [comment]
晚安好梦

**Comment by GuiterBoy** [comment]
还有, 记得学习debug技能, 以及学会分析前后端错误日志信息.

**Comment by GuiterBoy** [comment]
数据库是Studentss ?

**Comment by emanresu112358** [comment]
对的，数据库是Studentss

**Comment by emanresu112358** [comment]
终于复现了，是一个十分值得学习的项目。

**Comment by Zy123zhou** [comment]
你的main方法在哪啊  怎么运行起来啊

**Comment by GuJishang** [comment]
我部署成功了，打开后点登录一直弹出 登录失败! 服务器端发生异常! 。以下是控制台报错内容
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'gender' from result set.  Cause: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy20.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy21.login(Unknown Source)
	at pers.huangyuhui.sms.service.impl.AdminServiceImpl.login(AdminServiceImpl.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy25.login(Unknown Source)
	at pers.huangyuhui.sms.controller.SystemController.login(SystemController.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'gender' from result set.  Cause: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:83)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:521)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:402)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy44.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 62 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at org.apache.ibatis.type.CharacterTypeHandler.getNullableResult(CharacterTypeHandler.java:37)
	at org.apache.ibatis.type.CharacterTypeHandler.getNullableResult(CharacterTypeHandler.java:26)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)
	... 85 more

**Comment by NCHU-ZJJ** [comment]
> 终于复现了，是一个十分值得学习的项目。
请问你是如何解决
运行登陆弹出“登陆失败！服务器发生异常”这个问题的

**Comment by kk123m** [comment]
显示url错误是什么原因啊，打不开网页

**Comment by Wany2025** [comment]
> > 终于复现了，是一个十分值得学习的项目。
> > 请问你是如何解决
> > 运行登陆弹出“登陆失败！服务器发生异常”这个问题的
1.数据库表名是admin，和XML里的td_admin不同。
2.还有发现的问题就是那个XML里的登录部分的SQL，查的的是admin里的所有字段，但是数据库里的admin表只有两个属性，就是Aname,Apassword，所以把XML里那一段改成查询两个属性就好了，但是改好了还是有问题，即使登录一直密码错误，不知道怎么解决

**Comment by Wany2025** [comment]
我改成这样，就登陆进去了
    <select id="login" parameterType="loginForm" resultType="pers.huangyuhui.sms.bean.Admin">
        SELECT
            Aname AS name,
            Apassword AS password
        FROM admin
        WHERE Aname = #{username}
          AND Apassword = #{password}
    </select>
